### PR TITLE
Prevent excessive memory allocation while decoding

### LINKED ISSUE #29: Prevent excessive memory allocation while decoding
I played around with go-fuzz (https://github.com/dvyukov/go-fuzz) to find possible problems in this go package.

Until now I did not discover any crashes, but I found some unchecked memory allocations, where it is possible a huge amount of memory with specially crafted packets, because the respective lengths, privided in the sflow package are not checked against an upper limit.

I tried to find some reasonable maximum values and suggest:

* for maximum record length: MAX_PKT_SIZ (65536) from sflow reference implementation: https://github.com/sflow/sflowtool/blob/bd3df6e11bdf8261a42734c619abfe8b46e1202f/src/sflowtool.c#L4313
* for maximum header length: maximum transmission unit (MTU), as the header of a network packet may not exceed the MTU.

### PR DESCRIPTION
**Pull request by breml**
Enforce reasonable maximum values for record and header length while decoding sflow packets.

Fixes #29

### CODE REVIEW

File: decoder.go [hunk 1]
```diff
@@ -6,6 +6,20 @@ import (
...
+	// This maximum prevents from excessive memory allocation for decoding.
+	// The value is derived from MAX_PKT_SIZ 65536 in sflow reference implementation
+	// https://github.com/sflow/sflowtool/blob/bd3df6e11bdf8261a42734c619abfe8b46e1202f/src/sflowtool.c#L4313
+	MaximumRecordLength = 65536
+
+	// MaximumHeaderLength defines the maximum length in bytes, acceptable for packet flow samples while decoding.
+	// This maximum prevents from excessive memory allocation for decoding.
+	// The value is derived from INM_MAX_HEADER_SIZE 256 in sflow reference implementation
+	// https://github.com/sflow/sflowtool/blob/bd3df6e11bdf8261a42734c619abfe8b46e1202f/src/sflowtool.h#L28
+	MaximumHeaderLength = 256
```
Comment (Preetam) [inline decoder.go]: I'm not sure about this one. I typically sample more than 256 bytes, and Brocade allows you to capture up to 1300 (see [Specifying the maximum flow sample size](http://www.brocade.com/content/html/en/administration-guide/fastiron-08030-adminguide/GUID-0841A65C-F58D-417F-B0E3-9846539ED13C.html)).

I think 1300 is a better choice.

Comment (breml) [inline decoder.go]: I could not find any information about the maximum in the sflow specification. First my setting was 1500 and I corrected it in the second commit based on the sflowtool source code. I am fine with 1300 or 1500.  
The main issue is, the header length field in the sflow package is uint32, so the maximum would be 0xFFFFFFFF, respectively 4,294,967,295 bytes. And this is by far to much for the `make([]byte, f.HeaderSize+padding)`.

Comment (Preetam) [inline decoder.go]: I agree, let's not make it too high :). I'll let you choose either 1300 or 1500.

**Comment by Preetam** [comment]
LGTM besides what I described in the comment. Thanks for your help! :+1:

**Comment by breml** [comment]
I just reverted my last commit so we are back to 1500 for `MaximumHeaderLength`.
